Description:  CodeCommit/CodeBuild For Alexa Auto SDK Workshop
Resources:
  AlexaRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: alexa-auto-sdk
  InputArtifactS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'alexa-auto-app-input-artifact-${AWS::AccountId}'
  OutputArtifactS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'alexa-auto-app-output-artifact-${AWS::AccountId}'

  BuildTool:
    Type: AWS::CodeBuild::Project
    Properties: 
      Artifacts: 
          Location: !Sub 'alexa-auto-app-output-artifact-${AWS::AccountId}'
          Name: alexa-auto-apk-build
          NamespaceType: BUILD_ID
          Type: S3
      Environment: 
        ComputeType: BUILD_GENERAL1_2XLARGE
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      LogsConfig: 
        CloudWatchLogs: 
          Status: ENABLED
      Name: alexa-auto-app-build
      ServiceRole: !GetAtt CodebuildServiceRole.Arn
      Source: 
        Type: CODECOMMIT
        Location: !GetAtt AlexaRepo.CloneUrlHttp
  CodebuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: alexa-auto-app-code-build-service-role

